kind = "web"
previewPath = "/api"
title = "API Server"
version = "1.0.0"
id = "artifacts/api-server"
router = "path"

[[services]]
localPort = 22729
name = "web"
paths = ["/api"]

[services.development]
run = "pnpm install --frozen-lockfile && pnpm --filter @workspace/api-server run dev"

[services.production]

[services.production.build]
args = ["pnpm", "--filter", "@workspace/api-server", "run", "build"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = ["node", "--enable-source-maps", "artifacts/api-server/dist/index.mjs"]

[services.production.run.env]
PORT = "22729"
NODE_ENV = "production"

[services.production.health.startup]
path = "/api/healthz"

[services.env]
PORT = "22729"
